### PR TITLE
n0t curs3d enough

### PR DESCRIPTION
**Pull request by Arinerron**
GitHub issues was disabled so I made a PR to warn people instead!!!!!!!!!!!!!!!!!111111111111111two

### CODE REVIEW

**Comment by Arinerron** [comment]
anyway would recommend cursing it more

**Comment by Arinerron** [comment]
i changed my mind

**Comment by ammaraskar** [comment]
PULL REQUESTS WELCOME

**Comment by ammaraskar** [comment]
Your feedback has been taken into account and further cursing has been performed

**Comment by Arinerron** [comment]
Ty sir 🫡 My role model when cursing anything is always https://kevinhiggs.com/, hopefully you can get some inspiration from it.

**Pull request closed without merging**
